spring:
  profiles:
    active: test

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:file:./src/main/resources/sql/taco_cloud;AUTO_SERVER=TRUE; #以自动混合模式启动
    username: sa #默认数据库用户名
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tacocloud

taco:
  orders:
    page-size: 1
logging:
  level:
    root: debug
    sql: debug
    web: debug
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:file:./src/main/resources/sql/taco_cloud;AUTO_SERVER=TRUE; #以自动混合模式启动
    username: sa #默认数据库用户名
  sql:
    init:
      mode: always #自动运行数据库初始化脚本
      schema-locations: classpath:sql/schema.sql #表结构文件位置
      data-locations: classpath:sql/data.sql #表数据文件位置
  cassandra:
    keyspace-name: tacocloud
    schema-action: recreate
    local-datacenter: datacenter1
  data:
    mongodb:
      host: localhost
      port: 27017
      username: tacocloud
      password: tacocloud
      database: tacocloud
taco:
  orders:
    page-size: 1
logging:
  level:
    root: warn

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:tacocloud
    username: sa