spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:tacocloud}
    rest:
      base-path: /api
---
spring:
  data:
    mongodb:
      host: localhost #主机地址
      port: 27017 #服务器端口
      username: ${mongodb.username:tacocloud} #连接用户名
      password: ${MONGO_PASSWORD:tacocloud} #连接密码
      database: ${MONGO_DATABASE} #数据库名
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:file:./src/main/resources/sql/taco_cloud;AUTO_SERVER=TRUE; #以自动混合模式启动
    username: sa #默认数据库用户名
  sql:
    init:
      mode: always #自动运行数据库初始化脚本
      schema-locations: classpath:sql/schema.sql #表结构文件位置
      data-locations: classpath:sql/data.sql #表数据文件位置
  cassandra:
    keyspace-name: tacocloud
    schema-action: recreate
    local-datacenter: datacenter1

taco:
  orders:
    page-size: 5
logging:
  level:
    root: warn

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:tacocloud
    username: sa
  data:
    rest:
      base-path: api
server:
  port: 8443
  ssl:
    key-store: C:\Users\13223\mykeys.jks
    key-store-password: letmein
    key-password: letmein
logging:
  file:
    path: C:\Users\13223 #日志文件目录
    name: TacoCloud.log #日志文件名称
  level:
    root: warn #全局
    org.springframework.security: debug #指定包名
taco:
  orders:
    page-size: 6